[theme]
background = "#181818"
primary = "#FFFFFF"
secondary = "#FFFFFF"
title = "#7E62B3"
playing = "#7E62B3"
playing_selected = "#000000"
playing_bg = "#181818"
highlight = "#FFFFFF"
highlight_bg = "#7E62B3"
error = "#FFE4E4"
error_bg = "#A50000"
statusbar = "#7E62B3"
statusbar_progress = "#7E62B3"
statusbar_bg = "#000000"
cmdline = "#CBFFDE"
cmdline_bg = "#444444"
